#!/usr/bin/env python3
"""Generate include/fm_t9_dict.h - the English word list for T9 prediction.

Words come from the `wordfreq` package (pip install wordfreq), most frequent
first. Flood / medical / rescue words are moved to the front so they win ties
on the same key sequence (e.g. HELP before GELS). Re-run after editing BOOST:

    python3 tools/gen_t9_dict.py > include/fm_t9_dict.h
"""
import re
from wordfreq import top_n_list

N_WORDS = 9000
MAX_LEN = 14

BOOST = """
help sos rescue boat boats trapped stuck injured hurt bleeding medical medicine
medicines insulin dialysis oxygen pregnant baby babies child children elderly old
wheelchair bedridden sick fever diabetic heart attack emergency urgent please
water flood flooding rising roof terrace floor ground first second third fourth
fifth top food drinking milk power battery phone torch light dark night cold
evacuate evacuation safe unsafe danger current electric shock snake collapse
house home flat building street road camp relief shelter doctor nurse hospital
ambulance police fire people persons family mother father grandmother
grandfather amma appa patti thatha no yes ok okay need needs send come coming
here there now fast quick hours minutes stranded alone missing dead body
""".split()

words = []
seen = set()
for w in [b.upper() for b in BOOST] + [x.upper() for x in top_n_list("en", 40000)]:
    if not re.fullmatch(r"[A-Z]+", w) or len(w) > MAX_LEN or w in seen:
        continue
    seen.add(w)
    words.append(w)
    if len(words) >= N_WORDS:
        break

blob_bytes = sum(len(w) + 1 for w in words)
print("// GENERATED by tools/gen_t9_dict.py - do not edit by hand.")
print(f"// {len(words)} words, {blob_bytes} bytes. Frequency order, rescue words first.")
print("#pragma once")
print(f"#define FM_T9_WORD_COUNT {len(words)}")
print("static const char kFmT9Words[] =")
line = '    "'
for w in words:
    piece = w + "\\0"
    if len(line) + len(piece) > 96:
        print(line + '"')
        line = '    "'
    line += piece
print(line + '";')
